feat: Se mejoro como se maneja el pre-commit de husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,28 @@
 #!/bin/sh
+
+# Verificar el formato del código
 if ! pnpm check-format; then
-    echo "ERROR: Sú código no respeta la convenciones de formato, consulte la documentación o utlice el comando 'pnpm run format'." >&2
-    exit 1
+    echo "ERROR: Tu código no respeta las convenciones de formato."
+    echo "¿Deseas formatearlo ahora? (y/n)"
+    
+    # Leer la respuesta del usuario
+    read answer
+    
+    # Convertir la respuesta a minúsculas para manejar 'Y' y 'N' indistintamente
+    answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
+    
+    # Procesar la respuesta del usuario
+    if [ "$answer" = "y" ]; then
+        # Formatear el código
+        pnpm run format
+        echo "Se ha formateado el código."
+        exit 0
+    else
+        # Mostrar mensaje y salir con error
+        echo "No se realizó ningún formateo."
+        exit 1
+    fi
 fi
+
+exit 0
 
